# -*- coding: utf-8 -*-
"""p118

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/105ZezZjBpV7w5X-nbU0F3N0mx5j1ZI0l
"""

from google.colab import files
data_to_load=files.upload()

import pandas as pd
import plotly.express as px
df=pd.read_csv('data.csv')
print(df.head())
fig=px.scatter(df,x="Size",y="Light")
fig.show()

from sklearn.cluster import KMeans
X=df.iloc[:,[0,1]].values
print(X)

wcss=[]
for i in range (1,11):
  kmeans=KMeans(n_clusters=i,init='k-means++',random_state=42)
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10,5))
sns.lineplot(range(1,11),wcss,marker='o',color='maroon')
plt.title('the elbow methord')
plt.xlabel('number of clusters')
plt.ylabel("wcss")
plt.show()

kmeans=KMeans(n_clusters=3,init='k-means++',random_state=42)
y_kmeans=kmeans.fit_predict(X)

from itertools import filterfalse
plt.figure(figsize=(15,7))
sns.scatterplot(X[y_kmeans==0,0],X[y_kmeans==0,1],color='pink',label='cluster1')
sns.scatterplot(X[y_kmeans==1,0],X[y_kmeans==1,1],color='blue',label='cluster2')
sns.scatterplot(X[y_kmeans==2,0],X[y_kmeans==2,1],color='cyan',label='cluster3')
sns.scatterplot(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],color='black',label='centroids',size=100,marker=',')
plt.grid(False)
plt.title('cluster of flowers')
plt.xlabel('petelsize')
plt.ylabel('sepalsize')
plt.legend()
plt.show()